# -*- coding: utf-8 -*-
"""better_face_recogntion/best-match.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1goNW-cO6mb95JraCxcxoQbpRb8FmScD0
"""

!pip install face_recognition

import dlib

from google.colab.patches import cv2_imshow

import face_recognition

import matplotlib.pyplot as plt

import cv2

image = face_recognition.load_image_file('me1.jpg')

face_locations = face_recognition.face_locations(image)

face_landmarks_list = face_recognition.face_landmarks(image)

print(face_landmarks_list)

marshall = face_recognition.load_image_file("me1.jpg")

marshall_face_encoding = face_recognition.face_encodings(marshall)[0]

johnny = face_recognition.load_image_file("johnny-depp 2.jpg")

johnny_face_encoding = face_recognition.face_encodings(johnny)[0]

known_face_encodings = [marshall_face_encoding, johnny_face_encoding]

known_face_names = ["Marshall", "Johnny Depp"]

unknown_image = face_recognition.load_image_file("/content/me4.jpg")

face_locations = face_recognition.face_locations(marshall)

face_encodings = face_recognition.face_encodings(marshall, face_locations)

from PIL import Image, ImageDraw

pil_image = Image.fromarray(unknown_image)

draw =ImageDraw.Draw(pil_image)

face_distances = face_recognition.face_distance(known_face_encodings, marshall_face_encoding )

import numpy as np

best_match_index = np.argmin(face_distances)

name = "Unknown"
if [best_match_index]:
  name = known_face_names[best_match_index]

display(pil_image, name, best_match_index, face_landmarks_list)

